#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams, cycler
import itertools

# Load and organize data into dataframe
datafr = pd.read_csv('DiabetesDataset1.csv', header=0, index_col=0, engine='python')
print(datafr.shape)

                   


#features = ['sex', 'age','bp','s1','s2','s3','s4']
#combotuplelist = list(itertools.combinations(datafr.columns[:10], 5))
combolist = [list(tupl) for tupl in list(itertools.combinations(datafr.columns[2:10], 5))]

for idx, col1 in enumerate(range(len(combolist))):
    combolistfmt = combolist[idx][0]+'_'+combolist[idx][1]+'_'+combolist[idx][2]+'_'+combolist[idx][3]+'_'+combolist[idx][4]    
    pd.plotting.scatter_matrix(datafr[combolist[idx]])
    plt.suptitle(combolistfmt + ' Scatter Matrix')
    plt.savefig('scattermatrix_{}.png'.format(combolistfmt))
    

###############################################

for idx, col1 in enumerate(range(len(combolist))): 
    
    cmap = plt.cm.tab10
    rcParams['axes.prop_cycle'] = cycler(color=cmap(np.linspace(0, 1, 10)))
    
    fig, ax = plt.subplots()
    lines = ax.plot(datafr[combolist[idx]])
    combolistfmt = combolist[idx][0]+'_'+combolist[idx][1]+'_'+combolist[idx][2]+'_'+combolist[idx][3]+'_'+combolist[idx][4]    
    plt.legend((combolist[idx][0], combolist[idx][1], combolist[idx][2], combolist[idx][3], combolist[idx][4]), loc='upper right', bbox_to_anchor=(1.05, 1.0))
    
    plt.title(combolistfmt)
    plt.savefig('cycler_{}.png'.format(combolistfmt))


#################################################


 
#import seaborn as sns
#
#for idx, col1 in enumerate(range(len(combolist))): 
#    
#    sns.pairplot(datafr, x_vars=datafr[combolist[idx]].columns, y_vars='Y', aspect=0.7, kind = 'reg')
    













